let jsEmailObject = [
	{
	  "UserID": "USRML001",
	  "PersonName": "Linda Myers",
	  "Email": "Linda.Myers@skywalkeruni.ca",
	  "DateEmailSentSaved": "",
	  "TimeEmailSentSaved": "",
	  "DateEmailReceived": "April 21, 2021",
	  "TimeEmailReceived": "14:57:38",
	  "Draft": "Received",
	  "Subject": "The ship is almost finished",
	  "EmailText": "The ship is almost finished. Two or Three more things and we're in great shape. The sooner the better. Something's wrong here. No one has seen or knows anything about Threepio. He's been gone too long to have gotten lost. Relax. I'll talk to Lando and see what I can find out. I don't trust Lando. Well, I don't trust him, either. But he is my friend. Besides, we'll soon be gone. And then you're as good as gone, aren't you?"
	},
	{
	  "UserID": "USRML002",
	  "PersonName": "Mary Rivera",
	  "Email": "Mary.Rivera@skywalkeruni.ca",
	  "DateEmailSentSaved": "July 11, 1905",
	  "TimeEmailSentSaved": "11:33:31",
	  "DateEmailReceived": "",
	  "TimeEmailReceived": "",
	  "Draft": "No",
	  "Subject": "Identity",
	  "EmailText": "Oh, come on. How could you know my father? You don't even know who I am. Oh, I don't even know what I'm doing here. We're wasting our time. I cannot teach him. The boy has no patience. He will learn patience. Hmmm. Much anger in him, like his father. Was I any different when you taught me? Hah. He is not ready. Yoda! I am ready. I...Ben! I can be a Jedi. Ben, tell him I'm ready."
	},
	{
	  "UserID": "USRML003",
	  "PersonName": "Carol Leonard",
	  "Email": "Carol.Leonard@skywalkeruni.ca",
	  "DateEmailSentSaved": "July 11, 1905",
	  "TimeEmailSentSaved": "13:48:47",
	  "DateEmailReceived": "",
	  "TimeEmailReceived": "",
	  "Draft": "No",
	  "Subject": "Never doubted",
	  "EmailText": "I never doubted you for a second. Wonderful!"
	},
	{
	  "UserID": "USRML004",
	  "PersonName": "Barbara Mcdonald",
	  "Email": "Barbara.Mcdonald@skywalkeruni.ca",
	  "DateEmailSentSaved": "July 12, 1905",
	  "TimeEmailSentSaved": "14:12:33",
	  "DateEmailReceived": "",
	  "TimeEmailReceived": "",
	  "Draft": "No",
	  "Subject": "Small operation",
	  "EmailText": "So you see, since we're a small operation, we don't fall into the...uh...jurisdiction of the Empire. So you're part of the mining guild then? No, not actually. Our operation is small enough not to be noticed...which is advantageous for everybody since our customers are anxious to avoid attracting attention to themselves. Aren't you afraid the Empire's going to find out about this little operation and shut you down? That's always been a danger looming like a shadow over everything we've built here. But things have developed that will insure security. I've just made a deal that will keep the Empire out of here forever. We would be honored if you would join us. I had no choice. They arrived right before you did. I'm sorry. I'm sorry, too."
	},
	{
	  "UserID": "USRML005",
	  "PersonName": "Amanda Johnson",
	  "Email": "Amanda.Johnson@skywalkeruni.ca",
	  "DateEmailSentSaved": "",
	  "TimeEmailSentSaved": "",
	  "DateEmailReceived": "July 8, 1905",
	  "TimeEmailReceived": "14:21:48",
	  "Draft": "Received",
	  "Subject": "Hyperdrive",
	  "EmailText": "How would you know the hyperdrive is deactivated? The city's central computer told you? Artoo-Detoo, you know better than to trust a strange computer. Ouch! Pay attention to what you're doing!"
	},
	{
	  "UserID": "USRML006",
	  "PersonName": "Stephanie Davis",
	  "Email": "Stephanie.Davis@skywalkeruni.ca",
	  "DateEmailSentSaved": "",
	  "TimeEmailSentSaved": "",
	  "DateEmailReceived": "July 10, 1905",
	  "TimeEmailReceived": "13:56:52",
	  "Draft": "Received",
	  "Subject": "Bespin",
	  "EmailText": "Bespin. It's pretty far, but I think we can make it. A mining colony? Yeah, a Tibanna gas mine. Lando conned somebody out of it. We go back a long way, Lando and me. Can you trust him? No. But he has no love for the Empire, I can tell you that. Here we go, Chewie. Stand by. Detach! You do have your moments. Not many, but you have them."
	},
	{
	  "UserID": "USRML007",
	  "PersonName": "Jessica Miller",
	  "Email": "Jessica.Miller@skywalkeruni.ca",
	  "DateEmailSentSaved": "",
	  "TimeEmailSentSaved": "",
	  "DateEmailReceived": "July 9, 1905",
	  "TimeEmailReceived": "12:27:00",
	  "Draft": "Received",
	  "Subject": "Jedi counsel",
	  "EmailText": "Ready, are you? What know you of ready? For eight hundred years have I trained Jedi. My own counsel will I keep on who is to be trained! A Jedi must have the deepest commitment, the most serious mind. This one a long time have I watched. Never his mind on where he was. Hmm? What he was doing. Hmph. Adventure. Heh! Excitement. Heh! A Jedi craves not these things. You are reckless!"
	},
	{
	  "UserID": "USRML008",
	  "PersonName": "Sarah Smith",
	  "Email": "Sarah.Smith@skywalkeruni.ca",
	  "DateEmailSentSaved": "",
	  "TimeEmailSentSaved": "",
	  "DateEmailReceived": "July 7, 1905",
	  "TimeEmailReceived": "12:18:55",
	  "Draft": "Received",
	  "Subject": "Use the Force",
	  "EmailText": "Use the Force. Yes... Now...the stone. Feel it. Concentrate"
	},
	{
	  "UserID": "USRML009",
	  "PersonName": "Elizabeth Wilson",
	  "Email": "Elizabeth.Wilson@skywalkeruni.ca",
	  "DateEmailSentSaved": "",
	  "TimeEmailSentSaved": "",
	  "DateEmailReceived": "July 8, 1905",
	  "TimeEmailReceived": "13:56:59",
	  "Draft": "Received",
	  "Subject": "Lando C",
	  "EmailText": "Well, wait. This is interesting. Lando. Lando system? Lando's not a system, he's a man. Lando Calrissian"
	},
	{
	  "UserID": "USRML010",
	  "PersonName": "Ashley A Taylor",
	  "Email": "Ashley.A.Taylor@skywalkeruni.ca",
	  "DateEmailSentSaved": "July 10, 1905",
	  "TimeEmailSentSaved": "11:44:58",
	  "DateEmailReceived": "",
	  "TimeEmailReceived": "",
	  "Draft": "No",
	  "Subject": "Rendezvous",
	  "EmailText": "Good luck, Luke. See you at the rendezvous. Don't worry, Artoo. We're going, we're going"
	},
	{
	  "UserID": "USRML011",
	  "PersonName": "Ashley M Taylor",
	  "Email": "Ashley.M.Taylor@skywalkeruni.ca",
	  "DateEmailSentSaved": "July 9, 1905",
	  "TimeEmailSentSaved": "12:37:48",
	  "DateEmailReceived": "",
	  "TimeEmailReceived": "",
	  "Draft": "No",
	  "Subject": "Troop carriers assemble",
	  "EmailText": "All troop carriers will assemble at the north entrance. The heavy transport ships will leave as soon as they're loaded. Only two fighter escorts per ship. The energy shield can only be opened for a short time, so you'll have to stay very close to your transports. Two fighters against a Star Destroyer? The ion cannon will fire several shots to make sure that any enemy ships will be out of your flight path. When you've gotten past the energy shield, proceed directly to the rendezvous point. Understood? Right. Okay. Good luck. Okay. Everyone to your stations. Let's go!"
	},
	{
	  "UserID": "USRML012",
	  "PersonName": "Ashley S Taylor",
	  "Email": "Ashley.S.Taylor@skywalkeruni.ca",
	  "DateEmailSentSaved": "",
	  "TimeEmailSentSaved": "",
	  "DateEmailReceived": "July 11, 1905",
	  "TimeEmailReceived": "13:12:46",
	  "Draft": "Received",
	  "Subject": "Darth Vader",
	  "EmailText": "Lord Vader. You may take Captain Solo to Jabba the Hut after I have Skywalker. He's no good to me dead. He will not be permanently damaged. Lord Vader, what about Leia and the Wookiee? They must never again leave this city. That was never a condition of our agreement, nor was giving Han to this bounty hunter! Perhaps you think you're being treated unfairly. No. Good. It would be unfortunate if I had to leave a garrison here. This deal's getting worse all the time"
	},
	{
	  "UserID": "USRML013",
	  "PersonName": "Jessica Blaese",
	  "Email": "Jessica.Blaese@skywalkeruni.ca",
	  "DateEmailSentSaved": "",
	  "TimeEmailSentSaved": "",
	  "DateEmailReceived": "July 10, 1905",
	  "TimeEmailReceived": "11:10:44",
	  "Draft": "Received",
	  "Subject": "Re. Plan",
	  "EmailText": "Groups seven and ten will stay behind to fly the speeders. As soon as each transport is loaded, evacuation control will give clearance for immediate launch. Right, sir. Okay, that's it. Try it...Off! Turn it off! Turn it off! Off! Sir, it will take quite awhile to evacuate the T-forty-sevens"
	},
	{
	  "UserID": "USRML014",
	  "PersonName": "Heather James",
	  "Email": "Heather.James@skywalkeruni.ca",
	  "DateEmailSentSaved": "July 12, 1905",
	  "TimeEmailSentSaved": "14:34:38",
	  "DateEmailReceived": "",
	  "TimeEmailReceived": "",
	  "Draft": "No",
	  "Subject": "Echo Three to Echo Seven",
	  "EmailText": "Echo Three to Echo Seven. Han, old buddy, do you read me? Loud and clear, kid. What's up? Well, I finished my circle. I don't pick up any life readings. There isn't enough life on this ice cube to fill a space cruiser. The sensors are placed"
	},
	{
	  "UserID": "USRML015",
	  "PersonName": "Heather Jones",
	  "Email": "Heather.Jones@skywalkeruni.ca",
	  "DateEmailSentSaved": "July 11, 1905",
	  "TimeEmailSentSaved": "13:56:14",
	  "DateEmailReceived": "",
	  "TimeEmailReceived": "",
	  "Draft": "No",
	  "Subject": "Power generators",
	  "EmailText": "Distance to power generators? One-seven, decimal two-eight. Target. Maximum fire power. Transport, this is Solo. Better take off - I can't get to you. I'll get the princess out on the Falcon. But...but...but...where are you going? Uh...come back!! Wait! Wait for me! Wait! Stop! How"
	},
	{
	  "UserID": "USRML016",
	  "PersonName": "Xiang Miller",
	  "Email": "Xiang.Miller@skywalkeruni.ca",
	  "DateEmailSentSaved": "July 10, 1905",
	  "TimeEmailSentSaved": "11:23:19",
	  "DateEmailReceived": "",
	  "TimeEmailReceived": "",
	  "Draft": "Yes",
	  "Subject": "The Empire",
	  "EmailText": "The Empire is still out there. I don't think it's wise to... No time to discuss this as a committee"
	},
	{
	  "UserID": "USRML017",
	  "PersonName": "Bo Chang",
	  "Email": "Bo.Chang@skywalkeruni.ca",
	  "DateEmailSentSaved": "July 8, 1905",
	  "TimeEmailSentSaved": "13:57:12",
	  "DateEmailReceived": "",
	  "TimeEmailReceived": "",
	  "Draft": "Yes",
	  "Subject": "Re. Yoda",
	  "EmailText": "Now all I have to do is find this Yoda...if he even exists. Still...there's something familiar about this place. I feel like...I don't know... Like we're being watched!"
	},
	{
	  "UserID": "USRML018",
	  "PersonName": "Juan Ling",
	  "Email": "Juan.Ling@skywalkeruni.ca",
	  "DateEmailSentSaved": "July 11, 1905",
	  "TimeEmailSentSaved": "12:36:28",
	  "DateEmailReceived": "",
	  "TimeEmailReceived": "",
	  "Draft": "No",
	  "Subject": "The Fleet",
	  "EmailText": "Lord Vader, the fleet has moved out of light-speed, and we're preparing to...Aaagh! You have failed me for the last time, Admiral. Captain Piett. Yes, my lord. Make ready to land out troops beyond the energy shield and deploy the fleet so that nothing gets off that system. You are in command now, Admiral Piett. Thank you, Lord Vader"
	},
	{
	  "UserID": "USRML019",
	  "PersonName": "Bo Chang",
	  "Email": "Bo.Chang@skywalkeruni.ca",
	  "DateEmailSentSaved": "",
	  "TimeEmailSentSaved": "",
	  "DateEmailReceived": "July 8, 1905",
	  "TimeEmailReceived": "12:36:58",
	  "Draft": "Received",
	  "Subject": "Re. dialect",
	  "EmailText": "Sir, I don't know where your ship learned to communicate, but it has the most peculiar dialect. I believe, sir, it says that the power coupling on the negative axis has been polarized. I'm afraid you'll have to replace it. Well, of course I'll have to replace it. Here! "
	},
	{
	  "UserID": "USRML020",
	  "PersonName": "Tara K Sharma",
	  "Email": "Tara.K.Sharma@skywalkeruni.ca",
	  "DateEmailSentSaved": "",
	  "TimeEmailSentSaved": "",
	  "DateEmailReceived": "July 12, 1905",
	  "TimeEmailReceived": "11:50:37",
	  "Draft": "Received",
	  "Subject": "Re. Apology",
	  "EmailText": "Apology accepted, Captain Needa. Lord Vader, our ships have completed their scan of the area and found nothing. If the Millennium Falcon went into light-speed, it'll be on the other side of the galaxy by now. Alert all commands. Calculate every possible destination along their last know trajectory. Yes, my lord. We'll find them. Don't fail me again, Admiral. Alert all commands. Deploy the fleet"
	},
	{
	  "UserID": "USRML021",
	  "PersonName": "Tara Mohan Sharma",
	  "Email": "Tara.Mohan.Sharma@skywalkeruni.ca",
	  "DateEmailSentSaved": "",
	  "TimeEmailSentSaved": "",
	  "DateEmailReceived": "July 11, 1905",
	  "TimeEmailReceived": "14:09:22",
	  "Draft": "Received",
	  "Subject": "Power of the dark side",
	  "EmailText": "If you will not be turned, you will be destroyed. Young fool...only now, at the end, do you understand. Your feeble skills are no match for the power of the dark side. You have paid the price for your lack of vision. Father, please. Help me. Now, young Skywalker...you will die."
	},
	{
	  "UserID": "USRML022",
	  "PersonName": "Tara Sharma",
	  "Email": "Tara.Sharma@skywalkeruni.ca",
	  "DateEmailSentSaved": "",
	  "TimeEmailSentSaved": "",
	  "DateEmailReceived": "July 11, 1905",
	  "TimeEmailReceived": "12:21:50",
	  "Draft": "Received",
	  "Subject": "Lack of progress",
	  "EmailText": "That is correct, Commander. And he is most displeased with your apparent lack of progress. We shall double our efforts. I hope so, Commander, for your sake. The Emperor is not as forgiving as I am."
	},
	{
	  "UserID": "USRML023",
	  "PersonName": "Tarun Kumar",
	  "Email": "Tarun.Kumar@skywalkeruni.ca",
	  "DateEmailSentSaved": "",
	  "TimeEmailSentSaved": "",
	  "DateEmailReceived": "July 11, 1905",
	  "TimeEmailReceived": "13:11:15",
	  "Draft": "Received",
	  "Subject": "Fighters",
	  "EmailText": "Fighters coming in. There's too many of them! Accelerate to attack speed! Draw their fire away from the cruisers. Copy, Gold Leader."
	},
	{
	  "UserID": "USRML024",
	  "PersonName": "Tarun Rajkumar",
	  "Email": "Tarun.Rajkumar@skywalkeruni.ca",
	  "DateEmailSentSaved": "",
	  "TimeEmailSentSaved": "",
	  "DateEmailReceived": "July 8, 1905",
	  "TimeEmailReceived": "11:15:07",
	  "Draft": "Received",
	  "Subject": "Captain Solo",
	  "EmailText": "This can't be! Artoo, you're playing the wrong message. There will be no bargain. We're doomed. I will not give up my favorite decoration. I like Captain Solo where he is. Artoo, look! Captain Solo. And he's still frozen in carbonite. What could possibly have come over Master Luke. Is it something I did? He never expressed any unhappiness with my work. Oh! Oh! Hold it! Ohh!"
	},
	{
	  "UserID": "USRML025",
	  "PersonName": "Ravi Patel",
	  "Email": "Ravi.Patel@skywalkeruni.ca",
	  "DateEmailSentSaved": "July 11, 1905",
	  "TimeEmailSentSaved": "14:58:19",
	  "DateEmailReceived": "",
	  "TimeEmailReceived": "",
	  "Draft": "Yes",
	  "Subject": "Pleasantries",
	  "EmailText": "Lord Vader, this is an unexpected pleasure. We're honored by your presence. You may dispense with the pleasantries, Commander. I'm here to put you back on schedule. I assure you, Lord Vader, my men are working as fast as they can. Perhaps I can find new ways to motivate them. I tell you, this station will be operational as planned."
	},
	{
	  "UserID": "USRML026",
	  "PersonName": "Ranveer Singh",
	  "Email": "Ranveer.Singh@skywalkeruni.ca",
	  "DateEmailSentSaved": "July 9, 1905",
	  "TimeEmailSentSaved": "12:53:34",
	  "DateEmailReceived": "",
	  "TimeEmailReceived": "",
	  "Draft": "No",
	  "Subject": "St 321",
	  "EmailText": "Command station, this is ST 321. Code Clearance Blue. We're starting our approach. Deactivate the security shield. The security deflector shield will be deactivated when we have confirmation of your code transmission."
	},
	{
	  "UserID": "USRML027",
	  "PersonName": "Ranveer Singh Chandok",
	  "Email": "Ranveer.Singh.Chandok@skywalkeruni.ca",
	  "DateEmailSentSaved": "",
	  "TimeEmailSentSaved": "",
	  "DateEmailReceived": "July 11, 1905",
	  "TimeEmailReceived": "14:51:15",
	  "Draft": "Received",
	  "Subject": "FN 2187",
	  "EmailText": "Stand by... You are clear to proceed. We're starting our approach. Inform the commander that Lord Vader's shuttle has arrived. Yes, sir."
	}
]

let jsonEmailData = JSON.stringify(jsEmailObject)